apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hostpath-pod
  name: hostpath-pod
spec:
  containers:
  - image: busybox
    name: hostpath-pod
    resources: {}
    command: ['sh', '-c', 'cat /data/data.txt']
    volumeMounts:
    - name: host-data
      mountPath: /data

  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: host-data
    hostPath:
      path: /home/ssm-user
      type: Directory
status: {}
