apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-host
spec:
  storageClassName: slow 
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/ssm-user
    type: Directory
