apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blue-green-svcl
  name: blue-green-svc
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: blue-green-app
    color: blue
  type: ClusterIP
status:
  loadBalancer: {}
