apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ambassador-test 
  name: ambassador-test-webserver
spec:
  containers:
  - image: nginx:stable
    name: nginx 
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ambassador-test-svc
spec:
  selector:
    app: ambassador-test
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
