apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'echo $MESSAGE; cat /config/app.cfg']
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: message
    volumeMounts:
    - name: my-volume
      mountPath: /config

  volumes:
  - name: my-volume
    configMap:
      name: my-configmap
      items:
      - key: app.cfg
        path: app.cfg 
