apiVersion: v1
data:
  haproxy.cfg: |
    frontend ambassador
      bind *:8080
      default_backend ambassador_test_svc
    backend ambassador_test_svc
      server svc ambassador-test-svc:8081
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: haproxy-config
