apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar
  name: sidecar
spec:
  containers:
  - image: busybox
    name: sidecar-writer
    command: ["sh", "-c", 'echo "The writer wrote this!" >/output/data.txt; while true; do sleep 5; done']
    volumeMounts:
    - name: my-volume
      mountPath: /output
    resources: {}
  - image: busybox
    name: sidecar-reader
    command: ["sh", "-c", 'while true; do cat /input/data.txt; sleep 5; done']
    volumeMounts:
    - name: my-volume
      mountPath: /input
    resources: {}
  dnsPolicy: ClusterFirst
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
   - name: my-volume
     emptyDir: {}
status: {}
