apiVersion: v1
kind: Pod
metadata:
  name: shipping-web
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
  initContainers:
  - name: shipping-svc-checker
    image: busybox:1.27
    command: ['sh','-c','until nslookup shipping-svc; do echo waiting for service shipping-svc; sleep 2; done']
