apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-auth
  name: nginx-auth
spec:
  volumes:
  - name: configmap-volume
    configMap:
      name: nginx-config
  - name: secret-volume
    secret:
      secretName: nginx-passwd    
  containers:
  - image: nginx:1.19.1
    name: nginx-auth
    volumeMounts:
    - name: configmap-volume
      mountPath: /etc/nginx
    - name: secret-volume
      mountPath: /etc/nginx/conf
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
