apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: canary-svc
  name: canary-svc
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: canary-test
  type: ClusterIP
status:
  loadBalancer: {}
